public class HighTide {
	
    public static map<String, Decimal> populate() {
        map<String, Decimal> peakTides = new map<String, Decimal>();
        peakTides.put('Annapolis',1.11);
        peakTides.put('Atlantic City',2.96);
        peakTides.put('Bar Harbor',6.69);
        peakTides.put('Bergen Point West Reach',3.32);
        peakTides.put('Biscayne Bay',1.19);
        peakTides.put('Bishops Head',1.42);
        peakTides.put('Boston',5.9);
        peakTides.put('Brandywine Shoal Light',3.37);
        peakTides.put('Bridesburg',3.78);
        peakTides.put('Bridgeport', 4.2);
        peakTides.put('Burlington',4.36);
        peakTides.put('Cambridge',1.3);
        peakTides.put('Cape May',3.48);
        peakTides.put('Charleston',3.32);
        peakTides.put('Chatham',3.16);
        peakTides.put('Chesapeake Channel',1.79);
        peakTides.put('Chesapeake City',1.91);
        peakTides.put('Conimicut Light',3.07);
        peakTides.put('Cutler Farris Wharf',8.37);
        peakTides.put('Dahlgren',1.15);
        peakTides.put('Dames Point',1.92);
        peakTides.put('Delaware City',3.54);
        peakTides.put('Duck',2.25);
        peakTides.put('Duke Marine Lab',2.16);
        peakTides.put('Eastport',10.79);
        peakTides.put('Fall River',3.21);
        peakTides.put('Fernandina Beach',3.64);
        peakTides.put('Fort McHenry',1.29);
        peakTides.put('Fort Pulaski',4.22);
        peakTides.put('Kings Point',4.58);
        peakTides.put('Kiptopeke',1.75);
        peakTides.put('Lake Worth Pier',1.64);
        peakTides.put('Lewes',2.96);
        peakTides.put('Lewisetta',.97);
        peakTides.put('Marcus Hook',3.56);
        peakTides.put('Mayport',2.81);
        peakTides.put('Montauk',1.66);
        peakTides.put('Nantucket Island',2.24);
        peakTides.put('New Haven',3.86);
        peakTides.put('New London',1.82);
        peakTides.put('Newbold',4.53);
        peakTides.put('Newport',2.63);
        peakTides.put('Ocean City Inlet',1.51);
        peakTides.put('Oregon Inlet Marina',.77);
        peakTides.put('Philadelphia',3.76);
        peakTides.put('Port Canaveral',2.43);
        peakTides.put('Portland',5.92);
        peakTides.put('Providence',3.14);
        peakTides.put('Quonset Point',2.84);
        peakTides.put('Reedy Point',3.57);
        peakTides.put('Sandy Hook',3.33);
        peakTides.put('Sewells Point',1.65);
        peakTides.put('Ship John Shoal',3.8);
        peakTides.put('Solomons Island',1);
        peakTides.put('South Port Everglades',1.54);
        peakTides.put('Springmaid Pier',3.5);
        peakTides.put('The Battery',3.05);
        peakTides.put('Tolchester Beach',1.4);
        peakTides.put('Turkey Point Hudson River NERRS', 2.7);
        peakTides.put('USCG Station Hatteras',.2);
        peakTides.put('Wachapreague',2.6);
        peakTides.put('Washington',1.88);
        peakTides.put('Wells',5.61);
        peakTides.put('Wilmington',2.48);
        peakTides.put('Woods Hole',1.7);
        peakTides.put('Wrightsville Beach',2.9);
        peakTides.put('Yorktown USCG Training Center',1.7);
        return peakTides;
        
    }
    
}